
package cinemon.view.gui;

import cinemon.model.*;
import cinemon.model.exceptions.DoubleReserveException;
import java.awt.Color;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;

/**
 *
 * @author mtcraft22
 */
public class Butacas extends javax.swing.JFrame {

    /**
     * Creates new form Butacas
     */
    private Session se;
    private Butacas sc = this;
    public Butacas(Session se, Sala prev) {
        initComponents();
        this.se = se;
        int x = 100;  
        int y = 100;
        
             
        JButton butonvolver = new JButton("Volver");
        
        butonvolver.addActionListener(new ActionListener(){
                @Override
                public void actionPerformed(ActionEvent e) {
                    sc.dispose();
                    Sessions se = new Sessions(prev);
                    se.setVisible(true); 
                }
            });
        butonvolver.setBounds(10,10,100,50);
        this.add(butonvolver);
        for (var butacas : se.getButacas() ){
            for (var butaca : butacas){
                
                JButton butoncine = new JButton(Integer.toString(butaca.getId()));
                this.add(butoncine);
                butoncine.setVisible(true);
                if (butaca.isReservado()){
                    butoncine.setBackground(Color.GREEN);
                }
                butoncine.setBounds(x,y , 50,50);

                x += 55;
              
               butoncine.addActionListener((ActionEvent e) -> {
                   System.out.println("Pinchado: " + Integer.toString(butaca.getId()));
                   if(!butaca.isReservado()){
                       try {
                           butaca.setReservado(true);
                           butoncine.setBackground(Color.GREEN);
                       } catch (DoubleReserveException ex) {
                           System.out.println("Reserva no realizada");
                       }
                   }
                });
            
            }
            x = 100;
            y+= 55;
        
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
