
package cinemon.view.gui;

import cinemon.model.Sala;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JButton;

/**
 *
 * @author mtcraft22
 */
public class Sessions extends javax.swing.JFrame {

    /**
     * Creates new form Sessions
     */
    public Sessions(Sala sala) {
        initComponents();
        System.out.println("hola ");
        this.setTitle("Sessiones");
        
        int x = 0;
        int w = 50;
        Sessions sc = this;
        
        for (var i : sala.getSessiones()){
           
            JButton butoncine = new JButton(i.getPelicula().getTitulo());
            this.add(butoncine);
            butoncine.setVisible(true);
            butoncine.setBounds(x, w, w*2, w);
            x += w*3;
            
            butoncine.addActionListener(new ActionListener(){
                @Override
                public void actionPerformed(ActionEvent e) {
                    sc.dispose();
                    Butacas se = new Butacas(i,sala);
                    se.setVisible(true); 
                }
            });
            
            
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
